export const LIST_MOVIE_REQUEST = "listMovie/LIST_MOVIE_REQUEST";
export const LIST_MOVIE_SUCCESS = "listMovie/LIST_MOVIE_SUCCESS";
export const LIST_MOVIE_FAILED = "listMovie/LIST_MOVIE_FAILED";
export const LIST_MOVIE_COMMING_SUCCESS =
  "listMovieTest/LIST_MOVIE_COMMING_SUCCESS";
export const LIST_MOVIE_CHANGE_PAGE = "listMovieTest/LIST_MOVIE_CHANGE_PAGE";
