export const LIST_MOVIE_REQUEST = "listMovie/LIST_MOVIE_REQUEST";
export const LIST_MOVIE_SUCCESS = "listMovie/LIST_MOVIE_SUCCESS";
export const LIST_MOVIE_FAILED = "listMovie/LIST_MOVIE_FAILED";
export const LIST_MOVIE_COMMING_REQUEST =
  "listMovieTest/LIST_MOVIE_COMMING_REQUEST";
export const LIST_MOVIE_COMMING_SUCCESS =
  "listMovieTest/LIST_MOVIE_COMMING_SUCCESS";
export const LIST_MOVIE_COMMING_FAILED =
  "listMovieTest/LIST_MOVIE_COMMING_FAILED";
export const LIST_MOVIE_CHANGE_PAGE = "listMovieTest/LIST_MOVIE_CHANGE_PAGE";
//Fetch list lich chieu draft
export const LIST_SHOWTIME_DRAFT_REQUEST =
  "listMovie/LIST_SHOWTIME_DRAFT_REQUEST";
export const LIST_SHOWTIME_DRAFT_SUCCESS =
  "listMovie/LIST_SHOWTIME_DRAFT_SUCCESS";
export const LIST_SHOWTIME_DRAFT_FAILED =
  "listMovie/LIST_SHOWTIME_DRAFT_FAILED";
