export const LIST_BOOKING_CHAIR_REQUEST =
  "listBookingChair/LIST_BOOKING_CHAIR_REQUEST";
export const LIST_BOOKING_CHAIR_SUCCESS =
  "listBookingChair/LIST_BOOKING_CHAIR_SUCCESS";
export const LIST_BOOKING_CHAIR_FAILED =
  "listBookingChair/LIST_BOOKING_CHAIR_FAILED";
export const BOOKING_TICKET_REQUEST = "listBookingChair/BOOKING_TICKET_REQUEST";
export const BOOKING_TICKET_SUCCESS = "listBookingChair/BOOKING_TICKET_SUCCESS";
export const BOOKING_TICKET_FAILED = "listBookingChair/BOOKING_TICKET_FAILED";
