export const LightTheme = {
  // bgColor: "##fff",
  // color: "#7952b3",
  // borderButton: "1px solid #7952b3",
  // borderRadiusButton: "none",
  // hoverTextColor: "#fff",
  // hoverBgColor: "#7952b3",
  // borderColor: "#7952b3",
  navColor: "#fff",
  bgColor: "#f0f2f5",
  color: "#343a40",
  borderButton: "1px solid #343a40",
  borderRadiusButton: "none",
  hoverTextColor: "#fff",
  hoverBgColor: "#343a40",
  borderColor: "#d2d3d3",
};
